[package]
name = "gde"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }
itertools = "0.11.0"

[dependencies.uuid]
version = "1.4.1"
features = ["v4", "fast-rng"]

[dev-dependencies]
outdir-tempdir = "0.2"
tar = "0.4.40"
flate2 = "1.0.27"
glob = "0.3.1"
