[package]
name = "gde"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.19", features = ["derive"] }

[dependencies.uuid]
version = "1.4.1"
features = ["v4", "fast-rng"]
